### ISSUE TITLE
Request your work to be included in the awesome Zepp OS project

### ISSUE THREAD

**Issue by MyoungXUE** [melianmiko/zmake#4]
Hello @melianmiko 

Please allow me to introduce myself, I am Myoung XUE, an engineer from Zepp OS Team.

We have an awesome project https://github.com/zepp-health/awesome-zeppos, as the name suggests, where we include many projects from the community that are relevant to Zepp OS.

We noticed that several of your projects are publicly available on Github and would like to ask your permission to include them in the official awesome zeppos repository.

Hopefully, we can get your approval and your project will help more developers in the community.

**Comment by melianmiko** [comment]
Hello, @MyoungXUE 

Of course, I don't mind.

You can include my project(s) to that list as you want.
