### ISSUE TITLE
Could not find a version that satisfies the requirement PySide2==5.15.2.1 

### ISSUE THREAD

**Issue by emircanerkul** [melianmiko/zmake#5]
Hi @melianmiko 

Trying to build zmake but got this error.

```
Collecting Pillow==9.4.0
  Using cached Pillow-9.4.0-cp310-cp310-macosx_11_0_arm64.whl (3.0 MB)
ERROR: Could not find a version that satisfies the requirement PySide2==5.15.2.1 (from versions: none)
ERROR: No matching distribution found for PySide2==5.15.2.1
```

Mac M1 Python 3.10.11

**Comment by emircanerkul** [comment]
BTW, idk but ZeppPlayer was built via Mac M1 today. I just wanted to try from scratch and it just worked. Trying to same for this zmake but it started with errors..

**Comment by melianmiko** [comment]
Looks like PySide2 isn't available for macOS on arm64, it's Intel-only.

Try to install and use Intel version of Python.

![Screenshot_20230424_155653_Bromite_1.jpg](https://user-images.githubusercontent.com/67851274/233949073-9e16bc8e-669b-4acc-bd16-f0430397f9cb.jpg)

**Comment by emircanerkul** [comment]
@melianmiko okay, tried but this one but it automatically detect and install arm64 automatically how can i force to use intel version? 


<img width="504" alt="image" src="https://user-images.githubusercontent.com/11430795/233955590-3600b320-48e4-4ce9-82fe-b70e84200298.png">

Can i use this version?

<img width="504" alt="image" src="https://user-images.githubusercontent.com/11430795/233955859-8ec49156-d4fc-48c9-8436-28fc304ffc53.png">

**Comment by melianmiko** [comment]
I don't know, I have only access to an Intel-based macOS emulator ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

Only thing that I know: already build binaries works well on M1-based mac's.

**Comment by melianmiko** [comment]
`PySide6` is available for both Intel & ARM macOS, but migrating to that version will take... time. Mostly because 2 of 3 macOS virtual machines can't boot, again, and I'll need to reinstall OS at least in one of them.

I'll return to that later.

**Comment by emircanerkul** [comment]
@melianmiko I replaced and sent PR. But It does not built.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/11430795/233963116-17489a73-ead9-47c3-a166-4e3d8b633f56.png">

But I already have it 

➜  ~ whereis esbuild       
esbuild: /opt/homebrew/bin/esbuild

**Comment by melianmiko** [comment]
Looks like `/opt/homebrew/bin` isn't in system-level PATH variable.

I'll fix that in a few hours.

**Comment by emircanerkul** [comment]
@melianmiko okay, thank you

**Comment by melianmiko** [comment]
Do `git pull` and try to build & run again, added external tools lookup for `/opt/homebrew/bin` directory .

And also configured support of both PySide6 and PySide2, because Qt6 dropped support of macOS 10.15, which is used with a big part of Russian ZMake/ZeppPlayer users. (big part of macOS users of course, in total most of our people use windows 10-11)

**Comment by emircanerkul** [comment]
@melianmiko okay thank you now works really great

I think there is no --watch mode right? If that comes true that would be really great to see in live preview mode.

**Comment by melianmiko** [comment]
> Btw if we do not needed why this package already there

It won't be included into the `dist` directory and build bundle.

> `--watch`

Maybe, later...

**Comment by emircanerkul** [comment]
Thank you, have a good day..

**Comment by melianmiko** [comment]
I think this issue is fixed, and can be closed.

Upd. Ough, I didn't see previous messages...

**Comment by emircanerkul** [comment]
Yep
